## Copyright Pick-it NV 2018

bool                model_type        # true: positive model, false: negative model
sensor_msgs/Image   rgb_image
sensor_msgs/Image   depth_image
sensor_msgs/Image   mask_image
float64             scale_factor
int32               min_model_size
int32               max_model_size
---
bool                success # indicate successful run of triggered service
string              message # informational, e.g. for error messages
