# Copyright 2018, Pick-it NV.
# All rights reserved.

uint16      type
int32       old_file_id
int32       new_file_id
string      old_filename
string      new_filename
---
bool        success
string      message
