string    path
uint32    model_id
bool      is_enabled
int32     priority
---
bool      success # indicate successful run of triggered service
string    message # informational, e.g. for error messages
