# Copyright 2020, Pick-it NV.
# All rights reserved.

---
uint8 STATUS_SUCCESS          = 10
uint8 STATUS_FAILURE          = 20  # General failure (in case not known).
uint8 STATUS_NOT_WRITABLE     = 21

uint8     status              # Return status indicating success / failure.
