# Definitions of event codes.
# System specific events.
int32 EVENT_SYSTEM_STARTED = 1
int32 EVENT_SYSTEM_CONFIGURED = 2


# Camera specific events.
int32 EVENT_CAMERA_CONNECTED = 21
int32 EVENT_CAMERA_DISCONNECTED = 22

# TODO: Add many more events here.

# Robot-camera calibration specific events.
int32 EVENT_RC_CALIBRATION_SUCCEEDED = 31
int32 EVENT_RC_CALIBRATION_REQUESTED = 32

# Region of Interest (ROI) specific events.
int32 EVENT_ROI_TEACHING_SUCCEEDED = 41
int32 EVENT_BUILD_BACKGROUND_CLOUD_REQUESTED = 42

# Detection related events.
int32 EVENT_SINGLE_DETECTION_REQUESTED = 51
int32 EVENT_SINGLE_DETECTION_REQUESTED_DYNAMIC_PROTOCOL = 52
int32 EVENT_PROCESS_IMAGE = 53
int32 EVENT_DETECTION_FINISHED = 54

# Configuration related events.
int32 EVENT_CONFIGURATION_REQUESTED = 61
int32 EVENT_SAVE_ACTIVE_SETUP_REQUESTED = 62
int32 EVENT_SAVE_ACTIVE_PRODUCT_REQUESTED = 63

# Image capture time related events.
# Used for conveyor belt integration, for instance.
int32 EVENT_CAPTURE_IMAGE_GET_AGE_DYNAMIC_PROTOCOL = 71
int32 EVENT_CAPTURE_IMAGE_GET_TIMESTAMP_DYNAMIC_PROTOCOL = 72
int32 EVENT_CAPTURE_IMAGE = 73

# Snapshot related events.
int32 EVENT_SNAPSHOT_SAVED = 81
int32 EVENT_SNAPSHOT_LOADED = 82
int32 EVENT_SNAPSHOT_SAVING_FAILED = 83

# Teach specific events.
int32 EVENT_RETEACH_CYLINDER_REQUESTED = 90

# Robot specific events.
int32 EVENT_ROBOT_NEXT_OBJECT_REQUESTED = 101
int32 EVENT_ROBOT_NEXT_OBJECT_REQUESTED_DYNAMIC_PROTOCOL = 102
int32 EVENT_ROBOT_MODE_CHANGED = 103

# Application events.
int32 EVENT_SEND_ROBOT_EVENT = 111

# Definitions of event sources.
int32 SOURCE_UNSPECIFIED = 0
int32 SOURCE_SYSTEM = 1
int32 SOURCE_CAMERA = 2
int32 SOURCE_ROBOT = 3
int32 SOURCE_WEB_INTERFACE = 4

# Message fields.
time stamp
int32 code
int32 source          # Only relevant for events where the origin is not clear.
string message        # Additional payload message.
